### ISSUE TITLE
skipQuotingIfNotRequired is buggy

### ISSUE THREAD

**Issue by phiresky** [hediet/ts-typed-sql#31]
`.as("all")`  produces `AS all` which throws a `SyntaxError at "all"`

**Comment by hediet** [comment]
Is this due to `all` being a keyword? Which other keywords aren't allowed?

**Comment by phiresky** [comment]
probably yes. not sure, possibly all of
https://www.postgresql.org/docs/8.1/static/sql-keywords-appendix.html ?

2018-01-10 14:10 GMT+01:00 Henning Dieterichs <notifications@github.com>:

**Comment by phiresky** [comment]
full example: ` select * from (select 1) as all;`

**Comment by hediet** [comment]
Fixed in bad7ac6223c13d0f510c8d42c9c3bc0e9bd1736d. Hopefully, that fix is not bad :D
